# Generated by Django 4.2.7 on 2024-06-16 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeqr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='image',
            new_name='codeqr',
        ),
    ]
